### PR TITLE
base versioning on tags (offers more flexibility, made oacs-5-10 as d…

### PR DESCRIPTION
**Pull request by gustafn**
…efault)

get data from github (better than openacs.org, since we have from github tar files per tag)

### CODE REVIEW

**Comment by opsaaspo** [comment]
@gustafn Thanks for PR. I'll merge code some later.

**Comment by opsaaspo** [comment]
@gustafn FYI: My base version system control is fossil. I use the following algorithm: 
   -  push to fossil 
   - export to git (mirroring). 
   
I've added all your changes. But I'm not sure that I can merge your PR (see above).

**Comment by gustafn** [comment]
merging was also for me a pain due to your manual merging. We should find a better way to maintain this. One option would be to create a new repo under "openacs".

**Comment by oupfiz5** [comment]
for a long time - it doesn't make sense to refine

**Pull request closed without merging**
